### ISSUE TITLE
minGW compatibility

### ISSUE THREAD

**Issue by ctib** [tbeu/netCDF-DataReader#11]
I just encoutered an issue with the netCDF-DataReader within the BuildingSystems library using the minGW and minGW64 compiler.

The following error is written to dslog.txt
```Compiling and linking the model (GCC). 
 
dsmodel.c: In function 'equations_16':
dsmodel.c:7209:47: warning: passing argument 1 of 'StringTemporaryDense' from incompatible pointer type [-Wincompatible-pointer-types]
          StringElement( StringTemporaryDense( &DYNX(DYNAuxStr_,2+DYNStrInit(did_)),
                                               ^
In file included from C:/Program Files (x86)/Dymola 2017 FD01/Source/matrixop.h:11:0,
                 from dsmodel.c:7:
C:/Program Files (x86)/Dymola 2017 FD01/Source/matrixop1.h:490:27: note: expected 'const char **' but argument is of type 'char **'
 DYMOLA_STATIC StringArray StringTemporaryDense(String*d,SizeType ndims,...);
                           ^~~~~~~~~~~~~~~~~~~~
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
...
```
it works perfectly using Visual Studio
[dslog.txt](https://github.com/tbeu/netCDF-DataReader/files/1410914/dslog.txt)

**Comment by thorade** [comment]
I can reproduce the error using any of the three examples in the netCDF library, with Dymola 2018.
But is it a Dymola issue or a library issue? Not so sure.

**Comment by tbeu** [comment]
Seems like a tool issue for me. Tested with MinGW 4.7.2, 4.8.1 and MinGW-TDM 5.1.0.

**Comment by thorade** [comment]
@ctib It should work out of the box for all gcc versions that have a matching binary in the subfolders of `NcDataReader2/Resources/Library`:
https://github.com/modelica-3rdparty/netCDF-DataReader/tree/master/NcDataReader2/Resources/Library
