### ISSUE TITLE
libnetcdf.so error

### ISSUE THREAD

**Issue by DaJansenGit** [tbeu/netCDF-DataReader#15]
Hey i just read the information in this [issue here](https://github.com/UdK-VPT/BuildingSystems/issues/112). It seems like i have a similar problem. Im trying to run a FMU which uses the netCDF-DataReader. The import informations seems to be:

- program for FMU compilation: Dymola
- System: Linux 64 bit (Red Hat)
- Compiler: gcc (I think that it is the standard compiler for dymola on linux, unfortunaly i can't find out because i only have limited acces to the system) but if it's gcc its version 4.8.5

The FMU get's compiled but when i'm trying to run it with PyFMI i get an arror because of missing libnetcdf.so. The FMUChecker says:

`[FATAL][FMICAPI] Could not load the DLL: libnetcdf.so.7: cannot open shared object file: No such file or directory`
`[FATAL][FMUCHK] Could not create the DLL loading mechanism(C-API) for ME.`
`[INFO][FMUCHK] Model identifier for CoSimulation: OFHBuildingHiL_OFH_OFH_0HydraulikSQL`
`[INFO][FMILIB] Loading 'linux64' binary with 'default' platform types`
`[FATAL][FMICAPI] Could not load the DLL: libnetcdf.so.7: cannot open shared object file: No such file or directory`
`[FATAL][FMUCHK] Could not create the DLL loading mechanism(C-API) for CoSimulation.`

So i searched the internet for a libnetcdf.so for linux 64 bit and i found one [here](http://rpm.pbone.net/index.php3/stat/4/idpl/23588526/dir/redhat_el_5/com/netcdf4-4.1.2-23.2.x86_64.rpm.html).
But after inserting them into `Library/linux64` i still get the error and nothing changed. Is there anything i'm missing? I would also try to compile it myself, but havn't done this before and i'm not even sure if it would help ... Thanks for any help ;)

EDIT: Ok i think i understand the problem now, the compilation seems to be finde, but the DLL is missing on the system where i want to run the simulation, right? So i just copied the dll files to the usage system and ran the fmuchecker again. Now i get the message:
[FATAL][FMICAPI] Could not load the DLL: /usr/lib/libnetcdf.so.7: file too short
[FATAL][FMUCHK] Could not create the DLL loading mechanism(C-API) for ME.
[INFO][FMUCHK] Model identifier for CoSimulation: OFHBuildingHiL_OFH_OFH_0HydraulikSQL
[INFO][FMILIB] Loading 'linux64' binary with 'default' platform types
[FATAL][FMICAPI] Could not load the DLL: /usr/lib/libnetcdf.so.7: file too short
[FATAL][FMUCHK] Could not create the DLL loading mechanism(C-API) for CoSimulation.
So i don't think the problem is due to netCDF Reader, but if you want to provide help i would appreciate that

**Comment by DaJansenGit** [comment]
Ok i think i understand the problem now, the compilation seems to be finde, but the DLL is missing on the system where i want to run the simulation, right? So i just copied the dll files to the usage system and ran the fmuchecker again. Now i get the message:
`[FATAL][FMICAPI] Could not load the DLL: /usr/lib/libnetcdf.so.7: file too short`
`[FATAL][FMUCHK] Could not create the DLL loading mechanism(C-API) for ME.`
`[INFO][FMUCHK] Model identifier for CoSimulation: OFHBuildingHiL_OFH_OFH_0HydraulikSQL`
`[INFO][FMILIB] Loading 'linux64' binary with 'default' platform types`
`[FATAL][FMICAPI] Could not load the DLL: /usr/lib/libnetcdf.so.7: file too short`
`[FATAL][FMUCHK] Could not create the DLL loading mechanism(C-API) for CoSimulation.`
So i don't think the problem is due to netCDF Reader, but if you want to provide help i would appreciate that

**Comment by thorade** [comment]
Can you use the Red Hat package manager to install the `libnetcdf` package (or `libnetcdf-devel` or similar), instead of copying files manually?

https://trac.openmodelica.org/OpenModelica/ticket/4523

**Comment by DaJansenGit** [comment]
Hey thanks for your realy fast answer and sorry for my late reply!
I solved the problem by installing libnetcdf with conda and linking the binary files by doing this:
`  ln -s libnetcdf.so.11 libnetcdf.so.7`
I got the solution from [here](https://github.com/conda/conda/issues/3973)
Maybe this will help somebody with the same problem.
