### ISSUE TITLE
Additional files in the Resources folder

### ISSUE THREAD

**Issue by PMehrfeld** [tbeu/netCDF-DataReader#2]
Unfortunately, the delivered *.dll files are not sufficient for some of our computers. We would like to ask, if following files can be added in this repo:
- hdf5.dll 
- hdf5_hl.dll
- libcurl.dll
- zlib.dll
- netcdf.dll

The files come with the installation of netCDF ( [http://www.unidata.ucar.edu/downloads/netcdf/index.jsp](url) ), tested with v. 4.4.1.

**Comment by tbeu** [comment]
Yes, can do it. Only for Windows?

**Comment by PMehrfeld** [comment]
Yes, only for windows.

See PR #4
