### ISSUE TITLE
Annotation with relative Include/Library directories

### ISSUE THREAD

**Issue by PMehrfeld** [tbeu/netCDF-DataReader#3]
We are aiming to use the NcDataReader2 library in the AixLib (https://github.com/RWTH-EBC/AixLib/issues/313). Since we found some improvement regarding the annotation to include external files, it is not necessary anylonger to copy the files into the working directory.
The annotation is like:
`Include = "#include <ncDataReaderEA.h>", IncludeDirectory = "modelica://NcDataReader2/Resources/Include",`
Especially the `...Directory` commands are not implemented in the current master.
Similar, but with focus on 32 bit, is done in BuildingSystems: https://github.com/UdK-VPT/BuildingSystems/blob/master/BuildingSystems/Utilities/NcDataReader2/ncEasyGet1D.mo

Additionally, due to the 32/64 bit folder structure, the correct files will be chosen.
This was tested with Dymola 2017.

We could also create our own solution like in BuildingSystems. But in my opinion it is better to keep the dependency to this repo in order to stay up to date.

Is it okay, if we fork a branch and make a PR afterwards?

**Comment by tbeu** [comment]
> Is it okay, if we fork a branch and make a PR afterwards?

Sure, that's the way OSS contribution works and is stated in the readme file. Thanks!

**Comment by PMehrfeld** [comment]
Thanks for merging.
I close this issue due to #4

**Comment by thorade** [comment]
Minor comment @PMehrfeld :
All the links in your text are broken, you can just paste any URL as text and it will be converted:
https://github.com/RWTH-EBC/AixLib/issues/313
https://github.com/UdK-VPT/BuildingSystems/blob/master/BuildingSystems/Utilities/NcDataReader2/ncEasyGet1D.mo
This will also create the backlinks in the other issues.

**Comment by tbeu** [comment]
@thorade Links are fixed now.
