### ISSUE TITLE
MSL version

### ISSUE THREAD

**Issue by thorade** [tbeu/netCDF-DataReader#7]
This is just a question: 
We started to use netCDF-DataReader as a library (instead of including the bits and pieces in our own library). Our library uses MSL version 3.2.2, but that is mostly because Dymola is loading that version by default. netCDF-DataReader is using 3.2.1, and every time we open the two libraries together, Dymola wants to run an update script. That script does not really change anything, but it is annoying.
Would it be possible to also use MSL 3.2.2 in netCDF-DataReader or was the version on purpose? Does using one or the other version have any advantages?

Alternatively, I asked a question on stackoverflow, how to suppress the upgrade script dialog:
http://stackoverflow.com/questions/42343160/modelica-libraries-use-different-msl-version

**Comment by tbeu** [comment]
Yes, I can update to MSL v3.2.2.

**Comment by thorade** [comment]
Thanks
