### ISSUE TITLE
conflicts

### ISSUE THREAD

**Issue by thorade** [tbeu/netCDF-DataReader#8]
The [.travis.yml](https://github.com/tbeu/netCDF-DataReader/blob/master/.travis.yml) file contains some strange characters (lines 28-56) and I cannot pull the latest master anymore.

**Comment by tbeu** [comment]
This was work in progress to get the 32-bit libraries built on Travis CI (after drone.io deceased its service). After 17 hours of trying I gave up - with some corrupt state obviously. :disappointed:

**Comment by thorade** [comment]
Thanks for the effort, I'll discuss here whether we can help with compiling on travis. 
Independent of whether travis works or not, I get some strange merge conflicts, should I try to solve these and send a PR?

**Comment by tbeu** [comment]
No, it rather would help if I get Travis CI building the 32-bit libs.

**Comment by tbeu** [comment]
Please let me know if you have experience and time to help out getting the 32-bit libs built on Ubuntu Precise on Travis CI. This was the build script for drone.io, also Ubuntu 12.04 (Precise):
```sh
echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections
sudo rm /etc/apt/sources.list.d/google*
sudo rm /etc/apt/sources.list.d/ondrej*
sudo apt-get update -qq
sudo apt-get install -qq gcc-4.8-multilib
sudo apt-get install -qq libnetcdf-dev
echo 2 | sudo update-alternatives --config gcc
cd NcDataReader2/Resources
cmake -DMODELICA_ERROR_HANDLER:BOOL=ON -DNC_NOCHECK:BOOL=ON ./
make
./examples/PrintVersion
./examples/GenerateFile
./examples/Read1D
./examples/Read1DEasyAPI
./examples/Read2D
./examples/Read2DEasyAPI
cmake -DMODELICA_ERROR_HANDLER:BOOL=ON -DNC_NOCHECK:BOOL=OFF -DCMAKE_C_FLAGS="-O3 -DNDEBUG -fPIC" ./
make
cd src
tar cJf linux64.tar.xz libncDataReader2.a
rm -f libncDataReader2.a
rm -f -r *.o
cd ..
sudo apt-get purge libnetcdf-dev
sudo apt-get autoremove
sudo apt-get install -qq libc6-dev-i386
sudo apt-get install -qq libnetcdf6:i386
sudo apt-get install -qq libnetcdf-dev:i386
cmake -DMODELICA_ERROR_HANDLER:BOOL=ON -DNC_NOCHECK:BOOL=OFF -DCMAKE_C_FLAGS="-O3 -msse2 -DNDEBUG -m32 -fPIC" ./
make
cd src
tar cJf linux32.tar.xz libncDataReader2.a
```

**Comment by thorade** [comment]
My first problem was solved by resetting the master locally to the last working state
`git reset --hard 88023f4c9022bd32913d164045b25522eab2d645`

**Comment by tbeu** [comment]
Sorry, I used `git push --force master` pretty much the last weeks. Should have used a separate branch now that you are integrating the package.

**Comment by tbeu** [comment]
What was your second problem then?

**Comment by thorade** [comment]
No second problem, closing this issue.

**Comment by tbeu** [comment]
Good news, [Travis CI](https://travis-ci.org/tbeu/netCDF-DataReader) finally builds successfully.

**Comment by thorade** [comment]
Thanks again for all the effort.
https://travis-ci.org/tbeu/netCDF-DataReader/builds
